eliastre100_groups_create:
    path:     /groups/create
    defaults: { _controller: Eliastre100GroupsBundle:Groups:create }

eliastre100_groups_hire:
    path:     /groups/hire
    defaults: { _controller: Eliastre100GroupsBundle:Groups:hire }

eliastre100_groups_fire:
    path:     /groups/fire
    defaults: { _controller: Eliastre100GroupsBundle:Groups:fire }
